### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by PadowYT2** [PadowYT2/TailPad-Other#1]
<details>
<summary>Modules</summary>
<p>
<details>
<summary>Core</summary>
<p>
- [x] /
- [x] /:404
- [x] /:403
- [x] /:maintenance
- [x] /:custom_page
- [x] /:custom_basic_page
- [x] /terms
- [x] /privacy
- [x] /portal
- [x] /login
- [x] /register
- [x] /register/oauth
- [x] /forgot_password
- [x] /user/:not_exist
- [x] /leaderboards
- [ ] /status
- [ ] /profile
- [ ] /user/*
</p>
</details>
<details>
<summary>Forum</summary>
<p>
- [x] /
- [ ] /forum/*
</p>
</details>
- [ ] Cookie Consent
- [ ] Discord Integration
- [ ] [Wiki Pro Module](https://namelessmc.com/resources/resource/192-wiki-pro-module/)
- [ ] [McTrade](https://namelessmc.com/resources/resource/197-mctrade/)
- [ ] [Newsletter Module](https://namelessmc.com/resources/resource/205-newsletter-module/)
- [ ] [Tebex Integration](https://namelessmc.com/resources/resource/54-tebex-integration/)
- [ ] [Wiki](https://namelessmc.com/resources/resource/145-wiki/)
- [ ] [Frequently Asked Questions](https://namelessmc.com/resources/resource/184-frequently-asked-questions/)
- [ ] [Reviews](https://namelessmc.com/resources/resource/186-reviews/)
- [ ] [CraftingStore | Free donation platform](https://namelessmc.com/resources/resource/117-craftingstore--free-donation-platform/)
- [ ] [Rules Module](https://namelessmc.com/resources/resource/105-rules-module/)
- [ ] [Forms module](https://namelessmc.com/resources/resource/43-forms-module/)
- [ ] [CustomDropdown](https://namelessmc.com/resources/resource/195-customdropdown/)
- [ ] [Friends Module](https://namelessmc.com/resources/resource/42-friends-module/)
- [ ] [Staff Module](https://namelessmc.com/resources/resource/65-staff-module/)
- [ ] [[$] Chatbox Module](https://namelessmc.com/resources/resource/74--chatbox-module/)
- [ ] [Store Module](https://namelessmc.com/resources/resource/139-store-module/)
- [ ] [Suggestions System](https://namelessmc.com/resources/resource/129-suggestions-system/)
- [ ] [Vote Module](https://namelessmc.com/resources/resource/7-vote-module/)
- [ ] [Members List](https://namelessmc.com/resources/resource/6-members-list/)
- [ ] [NamelessMC Countdown](https://namelessmc.com/resources/resource/173-namelessmc-countdown/)
- [ ] [NamelessMC Resources](https://namelessmc.com/resources/resource/3-namelessmc-resources/)
- [ ] [Socialize](https://namelessmc.com/resources/resource/168-socialize/)
- [ ] [Gallery](https://namelessmc.com/resources/resource/193-gallery/)
- [ ] [Iframe](https://namelessmc.com/resources/resource/188-iframe/)
- [ ] [Badges](https://namelessmc.com/resources/resource/157-badges/)
- [ ] [Ghost Module - SUPERCHARGE your home page](https://namelessmc.com/resources/resource/183-ghost-module--supercharge-your-home-page/)
- [ ] [Donate Module](https://namelessmc.com/resources/resource/177-donate-module/)
</p>
</details>
- [x] Keep NamelessMC up to date
- [ ] Update checker
